exclude non compatible log4j 2 api from dependencies (#16)
- causes an error java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil